### ISSUE TITLE
line numbers

### ISSUE THREAD

**Issue by lukealford** [kazzkiq/CodeFlask.js#13]
only thing really missing, or not mentioned in the documentation.

**Comment by AndreYonadam** [comment]
I guess this can be done two ways. Adding an element to the left of the editor or within the placeholder text itself. Seems like it would be easier if it was within the placeholder itself since that would allow us to avoid syncing of the location of the elements when scrolling. However that might make it harder to style and also the number of digits might affect the sizing.

**Comment by kazzkiq** [comment]
I believe PR #31 fixes this issue.
