### ISSUE TITLE
iOS scroll text displacement

### ISSUE THREAD

**Issue by joesavage** [kazzkiq/CodeFlask.js#16]
Similar to issue #4, I'm seeing weird text displacement issues on iOS. Particularly, when trying to scroll upwards before the beginning or downwards past the end of code sections (where you might usually see rubber banding).

![image](https://cloud.githubusercontent.com/assets/1154110/13652884/ac1569ca-e646-11e5-888d-3c11640c73aa.jpeg)

**Comment by AndreYonadam** [comment]
I think it has to do with the padding of the element although I'm not 100% sure.

**Comment by kazzkiq** [comment]
It seems its an issue with the `onscroll` event delay and rubber band effect (at beggining and end of scrolling).

Here is an animated example of the Issue:
![2016-12-19 13_37_59](https://cloud.githubusercontent.com/assets/1953194/21318430/471fe3c6-c5f0-11e6-9e0d-b60a5ddc3638.gif)

I believe a good "fix" for this issue would be disabling opacity on `textarea` when scrolling on touch devices. This way the "shadow text" would not be displayed until user stopped scrolling the box.

**Comment by AndreYonadam** [comment]
Fixed in my pull request. At first I tried changing the text color, visibility and whatnot but that also affected the cursor. So what I ended up doing is using one simple CSS property that does the job. It no no longer produces the same unwanted result.
![dec-19-2016 14-08-04](https://cloud.githubusercontent.com/assets/4000593/21327793/700f0536-c5f6-11e6-922b-d7d8058b9ddd.gif)

**Comment by kazzkiq** [comment]
PR #25 fix this issue.

@AndreYonadam Thanks for the elegant and simple fix for this issue!
