### ISSUE TITLE
flasks.update()

### ISSUE THREAD

**Issue by mypala** [kazzkiq/CodeFlask.js#23]
Hi;

How can i use "update" funtion when i using "runAll" ??

**Comment by kazzkiq** [comment]
At the moment, you can only use `.onUpdate()` and `.update()` on single CodeFlask instances (using `.run()` instead of `.runAll()`.

A good work around this issue is to run a loop with `.run()` on all your CodeFlask instances, storing them in some variable and calling `.update()` individually.

Something like this:

```js
var codes = ['#my-code-1', '#my-code-2', '#my-code-3', ...]
var codeflasks = []

// run CodeFlask on each of your above selectors individually
codes.forEach(function(selector) {
  var flask = new CodeFlask;
  flask.run(selector);
  codeflasks.push(flask)
})

// update all the individual CodeFlask instances via loop
codeflasks.forEach(function(flask) {
  flask.update()
})
```
