### ISSUE TITLE
Help me to make it working

### ISSUE THREAD

**Issue by mrsof** [kazzkiq/CodeFlask.js#40]
Am I missing something ?

https://jsfiddle.net/MrSo/n1u0qjdd/

Thx for help

**Comment by kazzkiq** [comment]
It seems you've found a bug. There are some issues with language type while using `runAll` property.

I managed to fix the issue and make CodeFlask run [in this example](https://jsfiddle.net/ryhLoort/). But for some reason the style also seemed to break and make fonts misaligned.

Will have to dig this further.

**Comment by mrsof** [comment]
Hmmm ok but I did not manage to make this working either...

https://jsfiddle.net/MrSo/z5vns0qh/

**Comment by ivanalemunioz** [comment]
@kazzkiq I managed to fix the issue in [your example](https://jsfiddle.net/ryhLoort/1/), see changes on CodeFlask.prototype.renderOutput function

**Comment by kazzkiq** [comment]
@ivanalemunioz Nice! Thanks, I will be incorporating the fix in the project as soon as I can.

@mrsof For some reason, the external Codeflask JS you imported seems to be buggy. That's why in my example I removed your external resource and added CodeFlask directly to the JavaScript panel.

The bad part is that by changing the external resource ([using unpkg](https://unpkg.com/codeflask@0.2.0/src/codeflask.js)) your error vanishes, but anothe rone appears. I will have to take a look because CodeFlask seems to be breaking now.

**Comment by mrsof** [comment]
I used links you use in your own website !
https://kazzkiq.github.io/CodeFlask.js/js/vendor/codeflask.js

Anyway, I am pleased to have contibuted to your awesome script !
Thanks

**Comment by kazzkiq** [comment]
Reopening as this is a bug that must be corrected.

**Comment by mrsof** [comment]
Oops ok.
So maybe you should change the title.

**Comment by kazzkiq** [comment]
Using cdnjs link from `0.3.1` or jumping into `1.0` should prevent the issues in this thread.
