### ISSUE TITLE
Update CodeFlask on npm?

### ISSUE THREAD

**Issue by roelfjan** [kazzkiq/CodeFlask.js#52]
Is there a reason why the last update of the codeflask npm package was 11 months ago? I like to use it in my project as a npm package

**Comment by kazzkiq** [comment]
Just lack of time to push the new changes. [Done](https://www.npmjs.com/package/codeflask).

**Obs.:**<br>
There were some possible breaking changes, so beware when updating fro **`0.2.0`** to **`0.3.0`**.

**Obs<sup>2</sup>.:**<br>
According to SemVer, breaking changes should be added only in MAJOR versions, but since CodeFlask is still at beta (v0.x.x), and since I don't feel comfortable upgrading it to major `1.x`, I just pushed a MINOR version (`0.3.x`).
